name: Deploy to Ubuntu Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # Update the application
          cd /opt/wordpress-leads-sync
          
          # Stop the service
          sudo systemctl stop wordpress-leads-sync || true
          
          # Pull latest changes
          git pull origin main
          
          # Activate virtual environment and update dependencies
          source venv/bin/activate
          pip install -r requirements.txt
          
          # Restart the service
          sudo systemctl start wordpress-leads-sync
          
          # Check status
          sudo systemctl status wordpress-leads-sync --no-pager | head -n 10